# Generated by Django 5.1 on 2025-09-01 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero', models.PositiveIntegerField(max_length=10, verbose_name='Nº')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='aplicacao.cliente')),
            ],
        ),
    ]
