# Generated by Django 5.2.6 on 2025-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_venda_itemvenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('review_helpfulness', models.CharField(blank=True, max_length=20, null=True)),
                ('review_score', models.FloatField()),
                ('review_time', models.IntegerField()),
                ('review_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_review', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Nº'),
        ),
    ]
